version: '3'

services:
  server:
    image: 'erivelto/server-hotel-control'
    build:
      context: server
    container_name: server

    ports:
      - 3030:3030

  client:
    image: 'erivelto/client-hotel-control'
    build:
      context: hotel-client
    ports:
      - "4200:80"
    depends_on:
      - "server"

